package main

import (
	"github.com/mailgun/cli"
)

func NewEndpointCommand() cli.Command {
	return cli.Command{
		Name:  "endpoint",
		Usage: "Operations with vulcan endpoint",
	}
}

func NewEndpointSubcommands() []cli.Command {
	return []cli.Command{
		{
			Name:   "add",
			Usage:  "Add a new endpoint to location",
			Action: addEndpointAction,
			Flags: []cli.Flag{
				cli.StringFlag{"id", "", "endpoint id, autogenerated if empty"},
				cli.StringFlag{"up", "", "upstream id"},
				cli.StringFlag{"url", "", "url in form <scheme>://<host>:<port>"},
			},
		},
		{
			Name:  "rm",
			Usage: "Remove endpoint from location",
			Flags: []cli.Flag{
				cli.StringFlag{"id", "", "endpoint id"},
				cli.StringFlag{"up", "", "upstream id"},
			},
			Action: deleteEndpointAction,
		},
	}
}

func addEndpointAction(c *cli.Context) {
	printStatus(client(c).AddEndpoint(c.String("up"), c.String("id"), c.String("url")))
}

func deleteEndpointAction(c *cli.Context) {
	printStatus(client(c).DeleteEndpoint(c.String("up"), c.String("id")))
}
