package command

import (
	"github.com/mailgun/vulcand/Godeps/_workspace/src/github.com/codegangsta/cli"
)

func NewLocationCommand(cmd *Command) cli.Command {
	return cli.Command{
		Name:  "location",
		Usage: "Operations with vulcan locations",
		Subcommands: []cli.Command{
			{
				Name:  "add",
				Usage: "Add a new location to host",
				Flags: []cli.Flag{
					cli.StringFlag{"id", "", "id, autogenerated if empty"},
					cli.StringFlag{"host", "", "parent host"},
					cli.StringFlag{"path", "", " path, will be matched against request's path"},
					cli.StringFlag{"upstream, up", "", "upstream id"},
				},
				Action: cmd.addLocationAction,
			},
			{
				Name:   "rm",
				Usage:  "Remove a location from host",
				Action: cmd.deleteLocationAction,
				Flags: []cli.Flag{
					cli.StringFlag{"id", "", "id"},
					cli.StringFlag{"host", "", "parent host"},
				},
			},
			{
				Name:   "set_upstream",
				Usage:  "Update location upstream",
				Action: cmd.locationUpdateUpstreamAction,
				Flags: []cli.Flag{
					cli.StringFlag{"id", "", "id"},
					cli.StringFlag{"host", "", "parent host"},
					cli.StringFlag{"up", "", "new upstream id"},
				},
			},
		},
	}
}

func (cmd *Command) addLocationAction(c *cli.Context) {
	cmd.printStatus(cmd.client.AddLocation(c.String("host"), c.String("id"), c.String("path"), c.String("up")))
}

func (cmd *Command) locationUpdateUpstreamAction(c *cli.Context) {
	cmd.printStatus(cmd.client.UpdateLocationUpstream(c.String("host"), c.String("id"), c.String("up")))
}

func (cmd *Command) deleteLocationAction(c *cli.Context) {
	cmd.printStatus(cmd.client.DeleteLocation(c.String("host"), c.String("id")))
}
